package com.clashfit.ui.screens.session

import android.util.Log
import android.view.Choreographer
import android.view.TextureView
import androidx.compose.runtime.Composable
import androidx.compose.runtime.DisposableEffect
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberUpdatedState
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.viewinterop.AndroidView
import com.clashfit.core.model.CombatState
import com.google.android.filament.Colors
import com.google.android.filament.EntityManager
import com.google.android.filament.IndirectLight
import com.google.android.filament.LightManager
import com.google.android.filament.Renderer
import com.google.android.filament.View
import com.google.android.filament.utils.Manipulator
import com.google.android.filament.utils.ModelViewer
import com.google.android.filament.utils.Utils
import java.nio.ByteBuffer

private const val TAG = "ClashFit/boss3d"
private const val MODEL = "models/pacemaker.glb"

/**
 * THE PACEMAKER, as an actual 3D model.
 *
 * The model is generated by `tools/make-boss.py` rather than licensed, so its joint hierarchy is
 * exactly the one the combat model drives and its five clips are authored against the health
 * thresholds the game already uses. It renders into a TextureView with a transparent background so
 * it composites straight over the camera preview: the boss stands in the room with you.
 *
 * Every entry point here is guarded. Filament is native code that can fail to load on a device we
 * have never seen, and a fight that cannot start is worse than a fight with a simpler boss, so any
 * failure calls [onUnavailable] and the caller draws the Compose boss instead.
 */
@Composable
fun Boss3D(
    combat: CombatState,
    jolt: Float,
    modifier: Modifier = Modifier,
    onUnavailable: () -> Unit,
) {
    val state by rememberUpdatedState(combat)
    val hit by rememberUpdatedState(jolt)
    val unavailable by rememberUpdatedState(onUnavailable)

    // One attempt per composition. If the native library will not load there is no point retrying
    // every frame; the caller has already been told to draw something else.
    val ok = remember { runCatching { Utils.init() }.isSuccess }
    if (!ok) {
        DisposableEffect(Unit) {
            Log.w(TAG, "Filament native init failed; falling back to the drawn boss")
            unavailable()
            onDispose { }
        }
        return
    }

    AndroidView(
        modifier = modifier,
        factory = { ctx ->
            TextureView(ctx).also { view ->
                // Transparent, so the camera shows through everywhere the boss is not.
                view.isOpaque = false
                val rig = runCatching { BossRig(view, ctx.assets.open(MODEL).use { it.readBytes() }) }
                    .onFailure {
                        Log.w(TAG, "Could not start the 3D boss", it)
                        unavailable()
                    }
                    .getOrNull()
                view.setTag(R_RIG, rig)

                if (rig != null) {
                    val choreographer = Choreographer.getInstance()
                    val frame = object : Choreographer.FrameCallback {
                        override fun doFrame(frameTimeNanos: Long) {
                            choreographer.postFrameCallback(this)
                            runCatching { rig.frame(frameTimeNanos, state, hit) }
                                .onFailure {
                                    Log.w(TAG, "3D frame failed; falling back", it)
                                    choreographer.removeFrameCallback(this)
                                    unavailable()
                                }
                        }
                    }
                    view.setTag(R_LOOP, frame)
                    choreographer.postFrameCallback(frame)
                }
            }
        },
        onRelease = { view ->
            (view.getTag(R_LOOP) as? Choreographer.FrameCallback)?.let {
                Choreographer.getInstance().removeFrameCallback(it)
            }
            (view.getTag(R_RIG) as? BossRig)?.destroy()
            view.setTag(R_LOOP, null)
            view.setTag(R_RIG, null)
        },
    )
}

// Tag keys have to be unique ids, and any layout id will do for a private one.
private val R_RIG = android.R.id.icon1
private val R_LOOP = android.R.id.icon2

/**
 * The renderer and the rule for which clip plays.
 *
 * Filament's ModelViewer owns the engine, swap chain and asset. This adds the two things the game
 * needs on top: lighting that does not require shipping an environment map, and a mapping from
 * combat state to animation.
 */
private class BossRig(view: TextureView, glb: ByteArray) {

    private val viewer = ModelViewer(
        textureView = view,
        manipulator = Manipulator.Builder()
            .targetPosition(0f, 0f, 0f)
            // Slightly above and in front, looking down a little, so it reads as standing in
            // front of you rather than floating at eye level.
            .orbitHomePosition(0f, 0.28f, 2.55f)
            .build(Manipulator.Mode.ORBIT),
    )

    private var deathStartNanos = 0L
    private var hitStartNanos = 0L
    private var lastJolt = 0f
    private val clips = mutableMapOf<String, Int>()
    private var sun = 0

    init {
        viewer.loadModelGlb(ByteBuffer.wrap(glb))
        viewer.transformToUnitCube()

        // Composite over the camera: no skybox, a cleared transparent buffer, translucent blending.
        viewer.scene.skybox = null
        viewer.view.blendMode = View.BlendMode.TRANSLUCENT
        viewer.renderer.clearOptions = Renderer.ClearOptions().apply {
            clear = true
            // Filament takes the clear colour as doubles. Alpha zero is what lets the camera through.
            clearColor = doubleArrayOf(0.0, 0.0, 0.0, 0.0)
        }
        // A wide-ish lens. The boss is close, and a long lens would flatten it.
        viewer.cameraFocalLength = 30f

        // Lighting without an environment map. Shipping a KTX cubemap would cost megabytes for a
        // scene with one object in it; three-band spherical harmonics give the same soft ambient
        // for nine numbers. Warm from above, cool from below, which is how a room lights a figure.
        viewer.scene.indirectLight = IndirectLight.Builder()
            .irradiance(
                3,
                floatArrayOf(
                    0.62f, 0.60f, 0.66f,   // L0  ambient
                    0.22f, 0.22f, 0.28f,   // L1  vertical gradient
                    0.06f, 0.05f, 0.04f,
                    -0.04f, -0.04f, -0.02f,
                    0.02f, 0.02f, 0.03f,   // L2
                    0.01f, 0.01f, 0.01f,
                    -0.02f, -0.02f, -0.01f,
                    0.01f, 0.01f, 0.02f,
                    0.03f, 0.02f, 0.01f,
                ),
            )
            .intensity(34_000f)
            .build(viewer.engine)

        // A key light from the front left, warm, so the brass reads.
        sun = EntityManager.get().create()
        LightManager.Builder(LightManager.Type.DIRECTIONAL)
            .color(Colors.cct(5_600f)[0], Colors.cct(5_600f)[1], Colors.cct(5_600f)[2])
            .intensity(78_000f)
            .direction(-0.42f, -0.62f, -0.66f)
            .castShadows(false)
            .build(viewer.engine, sun)
        viewer.scene.addEntity(sun)

        viewer.animator?.let { a ->
            for (i in 0 until a.animationCount) clips[a.getAnimationName(i)] = i
        }
        Log.d(TAG, "boss loaded with clips ${clips.keys}")
    }

    /**
     * Advance one frame.
     *
     * The base clip comes from the phase. A hit is cross-faded over the top rather than replacing
     * it, so a recoil reads while the thing is still breathing, and death takes over completely
     * and does not loop.
     */
    fun frame(nowNanos: Long, combat: CombatState, jolt: Float) {
        val animator = viewer.animator
        if (animator != null && clips.isNotEmpty()) {
            if (combat.dead && deathStartNanos == 0L) deathStartNanos = nowNanos
            if (!combat.dead) deathStartNanos = 0L
            // A jolt spikes on a landed rep, so a rising edge is a new hit.
            if (jolt > 0.55f && lastJolt <= 0.55f) hitStartNanos = nowNanos
            lastJolt = jolt

            val seconds = nowNanos / 1_000_000_000.0f

            if (deathStartNanos != 0L) {
                val i = clips["death"] ?: 0
                val t = ((nowNanos - deathStartNanos) / 1_000_000_000.0f)
                    .coerceIn(0f, animator.getAnimationDuration(i))
                animator.applyAnimation(i, t)
            } else {
                val baseName = when {
                    combat.staggered -> "stagger"
                    combat.phaseLabel == "desperation" || combat.phaseLabel == "enrage" -> "enrage"
                    else -> "idle"
                }
                val base = clips[baseName] ?: 0
                val dur = animator.getAnimationDuration(base).coerceAtLeast(0.001f)
                animator.applyAnimation(base, seconds % dur)

                clips["hit"]?.let { hitClip ->
                    val since = (nowNanos - hitStartNanos) / 1_000_000_000.0f
                    val hitDur = animator.getAnimationDuration(hitClip)
                    if (hitStartNanos != 0L && since in 0f..hitDur) {
                        // Fade the recoil in fast and out over its own length.
                        animator.applyCrossFade(hitClip, since, (1f - since / hitDur).coerceIn(0f, 1f))
                    }
                }
            }
            animator.updateBoneMatrices()
        }
        viewer.render(nowNanos)
    }

    fun destroy() {
        runCatching {
            if (sun != 0) {
                viewer.scene.removeEntity(sun)
                viewer.engine.destroyEntity(sun)
                EntityManager.get().destroy(sun)
                sun = 0
            }
            viewer.destroyModel()
            viewer.destroy()
        }.onFailure { Log.w(TAG, "Tearing down the 3D boss failed", it) }
    }
}

/**
 * The boss, however this device can manage it.
 *
 * Tries the 3D model first and falls back to the Compose-drawn boss the moment Filament reports a
 * problem — a missing native library, a driver that will not give us a context, a frame that
 * throws. The fallback is not a placeholder: it is a complete boss with the same six states, so a
 * phone that cannot run the renderer still gets a fight rather than an apology.
 *
 * [allow3d] is the manual override from Settings. Automatic fallback only catches failures loud
 * enough to throw; a renderer that starts and looks wrong needs a switch a person can reach.
 * [onRenderer] reports which boss is actually on screen, so a caller can say so honestly.
 */
@Composable
fun BossStage(
    combat: CombatState,
    jolt: Float,
    shake: Float,
    modifier: Modifier = Modifier,
    allow3d: Boolean = true,
    onRenderer: (Boolean) -> Unit = {},
) {
    var use3d by remember { mutableStateOf(true) }
    val live = allow3d && use3d
    // Report what is actually on screen, not what was asked for. A caller that says "showing the
    // 3D model" while the fallback quietly took over is worse than saying nothing.
    LaunchedEffect(live) { onRenderer(live) }
    if (live) {
        Boss3D(combat, jolt, modifier, onUnavailable = { use3d = false })
    } else {
        BossFigure(combat, jolt, shake, modifier)
    }
}
