package com.clashfit.ui.screens.session

import android.util.Log
import android.view.Choreographer
import android.view.TextureView
import androidx.compose.runtime.Composable
import androidx.compose.runtime.DisposableEffect
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberUpdatedState
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.viewinterop.AndroidView
import com.clashfit.core.model.CombatState
import com.google.android.filament.Colors
import com.google.android.filament.EntityManager
import com.google.android.filament.IndirectLight
import com.google.android.filament.LightManager
import com.google.android.filament.Renderer
import com.google.android.filament.android.UiHelper
import com.google.android.filament.View
import com.google.android.filament.utils.Manipulator
import com.google.android.filament.utils.ModelViewer
import com.google.android.filament.utils.Utils
import java.nio.ByteBuffer
import com.google.android.filament.Engine

private const val TAG = "ClashFit/boss3d"
private const val MODEL = "models/pacemaker.glb"

/**
 * THE PACEMAKER, as an actual 3D model.
 *
 * The model is generated by `tools/make-boss.py` rather than licensed, so its joint hierarchy is
 * exactly the one the combat model drives and its five clips are authored against the health
 * thresholds the game already uses. It renders into a TextureView with a transparent background so
 * it composites straight over the camera preview: the boss stands in the room with you.
 *
 * Every entry point here is guarded. Filament is native code that can fail to load on a device we
 * have never seen, and a fight that cannot start is worse than a fight with a simpler boss, so any
 * failure calls [onUnavailable] and the caller draws the Compose boss instead.
 */
@Composable
fun Boss3D(
    combat: CombatState,
    jolt: Float,
    modifier: Modifier = Modifier,
    onUnavailable: () -> Unit,
    playerHit: HudEvent.PlayerHit? = null,
) {
    val state by rememberUpdatedState(combat)
    val hit by rememberUpdatedState(jolt)
    val unavailable by rememberUpdatedState(onUnavailable)

    // One attempt per composition. If the native library will not load there is no point retrying
    // every frame; the caller has already been told to draw something else.
    val ok = remember { runCatching { Utils.init() }.isSuccess }
    if (!ok) {
        DisposableEffect(Unit) {
            Log.w(TAG, "Filament native init failed; falling back to the drawn boss")
            unavailable()
            onDispose { }
        }
        return
    }

    // The renderer and its frame loop, held in composition rather than on the view.
    //
    // These used to live in view tags, which crashed on a real device: View.setTag(key, value)
    // rejects any key that is not an application-specific resource id, and a framework id like
    // android.R.id.icon1 is not one. Closing over a remembered holder is simpler anyway — both
    // lambdas are in the same composable scope, so there was never a reason to route them through
    // the view at all.
    val holder = remember { BossHolder() }

    AndroidView(
        modifier = modifier,
        factory = { ctx ->
            TextureView(ctx).also { view ->
                // Transparent, so the camera shows through everywhere the boss is not.
                view.isOpaque = false
                val rig = runCatching { BossRig(view, ctx.assets.open(MODEL).use { it.readBytes() }) }
                    .onFailure {
                        Log.w(TAG, "Could not start the 3D boss", it)
                        unavailable()
                    }
                    .getOrNull()
                holder.rig = rig

                if (rig != null) {
                    val choreographer = Choreographer.getInstance()
                    val frame = object : Choreographer.FrameCallback {
                        override fun doFrame(frameTimeNanos: Long) {
                            choreographer.postFrameCallback(this)
                            runCatching { rig.frame(frameTimeNanos, state, hit) }
                                .onFailure {
                                    Log.w(TAG, "3D frame failed; falling back", it)
                                    choreographer.removeFrameCallback(this)
                                    unavailable()
                                }
                        }
                    }
                    holder.loop = frame
                    choreographer.postFrameCallback(frame)
                }
            }
        },
        onRelease = {
            holder.loop?.let { Choreographer.getInstance().removeFrameCallback(it) }
            holder.rig?.destroy()
            holder.loop = null
            holder.rig = null
        },
    )
}

/** What one Boss3D owns and has to give back. */
private class BossHolder {
    var rig: BossRig? = null
    var loop: Choreographer.FrameCallback? = null
}

/**
 * The renderer and the rule for which clip plays.
 *
 * Filament's ModelViewer owns the engine, swap chain and asset. This adds the two things the game
 * needs on top: lighting that does not require shipping an environment map, and a mapping from
 * combat state to animation.
 */
private class BossRig(view: TextureView, glb: ByteArray) {

    /**
     * Our engine, not ModelViewer's.
     *
     * ModelViewer will happily create its own, but then the only way to give the memory back is
     * ModelViewer.destroy() — and on this device that path segfaults (see [destroy]). Owning the
     * engine means we can free every byte with one call that does not go near it.
     */
    private val engine: Engine = Engine.create()

    private val viewer = ModelViewer(
        textureView = view,
        engine = engine,
        // The swap chain has to be created transparent, and only the UiHelper can ask for that.
        // A transparent clear colour alone is not enough: without this the TextureView presents an
        // opaque black rectangle, which over a camera preview blacks out the room behind the boss.
        uiHelper = UiHelper(UiHelper.ContextErrorPolicy.DONT_CHECK).apply { isOpaque = false },
        manipulator = Manipulator.Builder()
            .targetPosition(0f, 0f, 0f)
            // Slightly above and in front, looking down a little, so it reads as standing in
            // front of you rather than floating at eye level.
            .orbitHomePosition(0f, 0.22f, 2.05f)
            .build(Manipulator.Mode.ORBIT),
    )

    private var deathStartNanos = 0L
    private var hitStartNanos = 0L
    private var lastJolt = 0f
    private val clips = mutableMapOf<String, Int>()
    private var sun = 0

    /**
     * Teardown happens once.
     *
     * Filament frees native memory that Kotlin cannot see, so a second destroy is a use-after-free
     * rather than a no-op. Compose can release an AndroidView more than once across a
     * configuration change, and the flag is cheaper than reasoning about when it will not.
     */
    private var destroyed = false

    init {
        viewer.loadModelGlb(ByteBuffer.wrap(glb))
        viewer.transformToUnitCube()

        // Composite over the camera: no skybox, a cleared transparent buffer, translucent blending.
        viewer.scene.skybox = null
        viewer.view.blendMode = View.BlendMode.TRANSLUCENT
        viewer.renderer.clearOptions = Renderer.ClearOptions().apply {
            clear = true
            // Filament takes the clear colour as doubles. Alpha zero is what lets the camera through.
            clearColor = doubleArrayOf(0.0, 0.0, 0.0, 0.0)
        }
        // A wide-ish lens. The boss is close, and a long lens would flatten it.
        viewer.cameraFocalLength = 30f

        // Lighting without an environment map. Shipping a KTX cubemap would cost megabytes for a
        // scene with one object in it; three-band spherical harmonics give the same soft ambient
        // for nine numbers. Warm from above, cool from below, which is how a room lights a figure.
        viewer.scene.indirectLight = IndirectLight.Builder()
            .irradiance(
                3,
                floatArrayOf(
                    0.62f, 0.60f, 0.66f,   // L0  ambient
                    0.22f, 0.22f, 0.28f,   // L1  vertical gradient
                    0.06f, 0.05f, 0.04f,
                    -0.04f, -0.04f, -0.02f,
                    0.02f, 0.02f, 0.03f,   // L2
                    0.01f, 0.01f, 0.01f,
                    -0.02f, -0.02f, -0.01f,
                    0.01f, 0.01f, 0.02f,
                    0.03f, 0.02f, 0.01f,
                ),
            )
            // Measured against ModelViewer's default exposure, which is set for bright
            // daylight. The first pass on device was roughly three times too bright and
            // washed every surface to the same pale grey.
            .intensity(19_000f)
            .build(viewer.engine)

        // A key light from the front left, warm, so the brass reads.
        sun = EntityManager.get().create()
        LightManager.Builder(LightManager.Type.DIRECTIONAL)
            .color(Colors.cct(5_600f)[0], Colors.cct(5_600f)[1], Colors.cct(5_600f)[2])
            .intensity(66_000f)
            .direction(-0.42f, -0.62f, -0.66f)
            .castShadows(false)
            .build(viewer.engine, sun)
        viewer.scene.addEntity(sun)

        viewer.animator?.let { a ->
            for (i in 0 until a.animationCount) clips[a.getAnimationName(i)] = i
        }
        Log.d(TAG, "boss loaded with clips ${clips.keys}")
    }

    /**
     * Advance one frame.
     *
     * The base clip comes from the phase. A hit is cross-faded over the top rather than replacing
     * it, so a recoil reads while the thing is still breathing, and death takes over completely
     * and does not loop.
     */
    fun frame(nowNanos: Long, combat: CombatState, jolt: Float) {
        val animator = viewer.animator
        if (animator != null && clips.isNotEmpty()) {
            if (combat.dead && deathStartNanos == 0L) deathStartNanos = nowNanos
            if (!combat.dead) deathStartNanos = 0L
            // A jolt spikes on a landed rep, so a rising edge is a new hit.
            if (jolt > 0.55f && lastJolt <= 0.55f) hitStartNanos = nowNanos
            lastJolt = jolt

            val seconds = nowNanos / 1_000_000_000.0f

            if (deathStartNanos != 0L) {
                val i = clips["death"] ?: 0
                val t = ((nowNanos - deathStartNanos) / 1_000_000_000.0f)
                    .coerceIn(0f, animator.getAnimationDuration(i))
                animator.applyAnimation(i, t)
            } else {
                val baseName = when {
                    combat.staggered -> "stagger"
                    combat.phaseLabel == "desperation" || combat.phaseLabel == "enrage" -> "enrage"
                    else -> "idle"
                }
                val base = clips[baseName] ?: 0
                val dur = animator.getAnimationDuration(base).coerceAtLeast(0.001f)
                animator.applyAnimation(base, seconds % dur)

                clips["hit"]?.let { hitClip ->
                    val since = (nowNanos - hitStartNanos) / 1_000_000_000.0f
                    val hitDur = animator.getAnimationDuration(hitClip)
                    if (hitStartNanos != 0L && since in 0f..hitDur) {
                        // Fade the recoil in fast and out over its own length.
                        animator.applyCrossFade(hitClip, since, (1f - since / hitDur).coerceIn(0f, 1f))
                    }
                }
            }
            animator.updateBoneMatrices()
        }
        viewer.render(nowNanos)
    }

    /**
     * Give everything back.
     *
     * Each step is guarded on its own, because ModelViewer registers its own detach listener and
     * may already have destroyed the engine by the time Compose releases the view. Finding the
     * scene already gone is the normal case on a back press, not a fault, so it is not logged as
     * one — but a step that fails for some other reason must not stop the steps after it.
     */
    fun destroy() {
        if (sun != 0) {
            val entity = sun
            sun = 0
            runCatching { viewer.scene.removeEntity(entity) }
            runCatching { viewer.engine.destroyEntity(entity) }
            runCatching { EntityManager.get().destroy(entity) }
        }
        // Neither viewer.destroyModel() nor viewer.destroy() is called here, and neither may be.
        //
        // Both roads lead to ResourceLoader.asyncCancelLoad(), which segfaults on this device:
        // destroy() calls destroyModel() itself, and destroyModel() calls asyncCancelLoad()
        // unconditionally, before it has even looked at whether there is an asset. The model is
        // loaded synchronously by loadModelGlb, so there is no async load to cancel and the native
        // side walks a pointer it never set. That is a SIGSEGV, not an exception: runCatching
        // cannot hold it, no Java stack is written, and the crash log stays empty because the
        // process is gone before the handler runs. It killed the app every single time a fight
        // screen closed. Read out of the tombstone: destroy -> destroyModel -> asyncCancelLoad+20.
        //
        // So the engine is ours (see the field above) and we give it back directly. Engine.destroy
        // frees the asset, the buffers, the textures and the swap chain in one call, on the native
        // side, without going through the loader at all. What leaks is a ModelViewer wrapper of a
        // few Kotlin objects; what would otherwise leak is the whole GPU allocation.
        if (destroyed) return
        destroyed = true
        runCatching { engine.destroy() }
            .onFailure { Log.d(TAG, "The 3D boss was already torn down", it) }
    }
}

/**
 * The boss, however this device can manage it.
 *
 * Tries the 3D model first and falls back to the Compose-drawn boss the moment Filament reports a
 * problem — a missing native library, a driver that will not give us a context, a frame that
 * throws. The fallback is not a placeholder: it is a complete boss with the same six states, so a
 * phone that cannot run the renderer still gets a fight rather than an apology.
 *
 * [allow3d] is the manual override from Settings. Automatic fallback only catches failures loud
 * enough to throw; a renderer that starts and looks wrong needs a switch a person can reach.
 * [onRenderer] reports which boss is actually on screen, so a caller can say so honestly.
 */
@Composable
fun BossStage(
    combat: CombatState,
    jolt: Float,
    shake: Float,
    modifier: Modifier = Modifier,
    allow3d: Boolean = true,
    onRenderer: (Boolean) -> Unit = {},
    playerHit: HudEvent.PlayerHit? = null,
) {
    var use3d by remember { mutableStateOf(true) }
    val live = allow3d && use3d
    // Report what is actually on screen, not what was asked for. A caller that says "showing the
    // 3D model" while the fallback quietly took over is worse than saying nothing.
    LaunchedEffect(live) { onRenderer(live) }
    if (live) {
        Boss3D(combat, jolt, modifier, onUnavailable = { use3d = false }, playerHit = playerHit)
    } else {
        BossFigure(combat, jolt, shake, modifier, playerHit = playerHit)
    }
}
